_prefs: 
  baselayer: ''
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -123.3984375
  - 48.29963964777107
  - 8
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
mtime: 1397360268724
name: water
scale: 1
source: "tilejson+http://localhost:8080/index.json"
#source: "tmsource:///Users/dane/projects/water-polygons/source.tm2"
styles: 
  - style.mss
template: ''
